<?php
/**
 * @var \Its\Config\ComponentInterface $this
 */

return [
    "IBLOCK_TYPE" => $this->arParentParams["IBLOCK_TYPE"],
    "IBLOCK_ID" => $this->arParentParams["IBLOCK_ID"],
    "ELEMENT_SORT_FIELD2" => $this->arParentParams["ELEMENT_SORT_FIELD2"],
    "ELEMENT_SORT_ORDER2" => $this->arParentParams["ELEMENT_SORT_ORDER2"],
    "PROPERTY_CODE" => $this->arParentParams["LIST_PROPERTY_CODE"],
    "PROPERTY_CODE_MOBILE" => $this->arParentParams["LIST_PROPERTY_CODE_MOBILE"],
    "META_KEYWORDS" => $this->arParentParams["LIST_META_KEYWORDS"],
    "META_DESCRIPTION" => $this->arParentParams["LIST_META_DESCRIPTION"],
    "BROWSER_TITLE" => $this->arParentParams["LIST_BROWSER_TITLE"],
    "SET_LAST_MODIFIED" => $this->arParentParams["SET_LAST_MODIFIED"],
    "INCLUDE_SUBSECTIONS" => $this->arParentParams["INCLUDE_SUBSECTIONS"],
    "BASKET_URL" => $this->arParentParams["BASKET_URL"],
    "ACTION_VARIABLE" => $this->arParentParams["ACTION_VARIABLE"],
    "PRODUCT_ID_VARIABLE" => $this->arParentParams["PRODUCT_ID_VARIABLE"],
    "SECTION_ID_VARIABLE" => $this->arParentParams["SECTION_ID_VARIABLE"],
    "SECTION_ID" => $this->arParentResult['VARIABLES']['SECTION_ID'],
    "PRODUCT_QUANTITY_VARIABLE" => $this->arParentParams["PRODUCT_QUANTITY_VARIABLE"],
    "PRODUCT_PROPS_VARIABLE" => $this->arParentParams["PRODUCT_PROPS_VARIABLE"],
    "FILTER_NAME" => $this->arParentParams["FILTER_NAME"],
    "CACHE_TYPE" => $this->arParentParams["CACHE_TYPE"],
    "CACHE_TIME" => $this->arParentParams["CACHE_TIME"],
    "CACHE_FILTER" => $this->arParentParams["CACHE_FILTER"],
    "CACHE_GROUPS" => $this->arParentParams["CACHE_GROUPS"],
    "SET_TITLE" => $this->arParentParams["SET_TITLE"],
    "MESSAGE_404" => $this->arParentParams["~MESSAGE_404"],
    "SET_STATUS_404" => $this->arParentParams["SET_STATUS_404"],
    "SHOW_404" => $this->arParentParams["SHOW_404"],
    "FILE_404" => $this->arParentParams["FILE_404"],
    "DISPLAY_COMPARE" => $this->arParentParams["USE_COMPARE"],
    "PAGE_ELEMENT_COUNT" => $this->arParentParams["PAGE_ELEMENT_COUNT"],
    "LINE_ELEMENT_COUNT" => $this->arParentParams["LINE_ELEMENT_COUNT"],
    "PRICE_CODE" => $this->arParentParams["~PRICE_CODE"],
    "USE_PRICE_COUNT" => $this->arParentParams["USE_PRICE_COUNT"],
    "SHOW_PRICE_COUNT" => $this->arParentParams["SHOW_PRICE_COUNT"],

    "PRICE_VAT_INCLUDE" => $this->arParentParams["PRICE_VAT_INCLUDE"],
    "USE_PRODUCT_QUANTITY" => $this->arParentParams['USE_PRODUCT_QUANTITY'],
    "ADD_PROPERTIES_TO_BASKET" => (isset($this->arParentParams["ADD_PROPERTIES_TO_BASKET"]) ? $this->arParentParams["ADD_PROPERTIES_TO_BASKET"] : ''),
    "PARTIAL_PRODUCT_PROPERTIES" => (isset($this->arParentParams["PARTIAL_PRODUCT_PROPERTIES"]) ? $this->arParentParams["PARTIAL_PRODUCT_PROPERTIES"] : ''),
    "PRODUCT_PROPERTIES" => (isset($this->arParentParams["PRODUCT_PROPERTIES"]) ? $this->arParentParams["PRODUCT_PROPERTIES"] : []),

    "DISPLAY_TOP_PAGER" => $this->arParentParams["DISPLAY_TOP_PAGER"],
    "DISPLAY_BOTTOM_PAGER" => $this->arParentParams["DISPLAY_BOTTOM_PAGER"],
    "PAGER_TITLE" => $this->arParentParams["PAGER_TITLE"],
    "PAGER_SHOW_ALWAYS" => $this->arParentParams["PAGER_SHOW_ALWAYS"],
    "PAGER_TEMPLATE" => $this->arParentParams["PAGER_TEMPLATE"],
    "PAGER_DESC_NUMBERING" => $this->arParentParams["PAGER_DESC_NUMBERING"],
    "PAGER_DESC_NUMBERING_CACHE_TIME" => $this->arParentParams["PAGER_DESC_NUMBERING_CACHE_TIME"],
    "PAGER_SHOW_ALL" => $this->arParentParams["PAGER_SHOW_ALL"],
    "PAGER_BASE_LINK_ENABLE" => $this->arParentParams["PAGER_BASE_LINK_ENABLE"],
    "PAGER_BASE_LINK" => $this->arParentParams["PAGER_BASE_LINK"],
    "PAGER_PARAMS_NAME" => $this->arParentParams["PAGER_PARAMS_NAME"],
    "LAZY_LOAD" => $this->arParentParams["LAZY_LOAD"],
    "MESS_BTN_LAZY_LOAD" => $this->arParentParams["~MESS_BTN_LAZY_LOAD"],
    "LOAD_ON_SCROLL" => $this->arParentParams["LOAD_ON_SCROLL"],

    "OFFERS_CART_PROPERTIES" => (isset($this->arParentParams["OFFERS_CART_PROPERTIES"]) ? $this->arParentParams["OFFERS_CART_PROPERTIES"] : []),
    "OFFERS_FIELD_CODE" => $this->arParentParams["LIST_OFFERS_FIELD_CODE"],
    "OFFERS_PROPERTY_CODE" => (isset($this->arParentParams["LIST_OFFERS_PROPERTY_CODE"]) ? $this->arParentParams["LIST_OFFERS_PROPERTY_CODE"] : []),
    "OFFERS_SORT_FIELD" => $this->arParentParams["OFFERS_SORT_FIELD"],
    "OFFERS_SORT_ORDER" => $this->arParentParams["OFFERS_SORT_ORDER"],
    "OFFERS_SORT_FIELD2" => $this->arParentParams["OFFERS_SORT_FIELD2"],
    "OFFERS_SORT_ORDER2" => $this->arParentParams["OFFERS_SORT_ORDER2"],
    "OFFERS_LIMIT" => (isset($this->arParentParams["LIST_OFFERS_LIMIT"]) ? $this->arParentParams["LIST_OFFERS_LIMIT"] : 0),

//    "SECTION_URL" => $this->arParentResult["FOLDER"].$this->arParentResult["URL_TEMPLATES"]["section"],
//    "DETAIL_URL" => $this->arParentResult["FOLDER"].$this->arParentResult["URL_TEMPLATES"]["element"],
    "USE_MAIN_ELEMENT_SECTION" => $this->arParentParams["USE_MAIN_ELEMENT_SECTION"],
    'CONVERT_CURRENCY' => $this->arParentParams['CONVERT_CURRENCY'],
    'CURRENCY_ID' => $this->arParentParams['CURRENCY_ID'],
    'HIDE_NOT_AVAILABLE' => $this->arParentParams["HIDE_NOT_AVAILABLE"],
    'HIDE_NOT_AVAILABLE_OFFERS' => $this->arParentParams["HIDE_NOT_AVAILABLE_OFFERS"],

    'LABEL_PROP' => $this->arParentParams['LABEL_PROP'],
    'LABEL_PROP_MOBILE' => $this->arParentParams['LABEL_PROP_MOBILE'],
    'LABEL_PROP_POSITION' => $this->arParentParams['LABEL_PROP_POSITION'],
    'ADD_PICT_PROP' => $this->arParentParams['ADD_PICT_PROP'],
    'PRODUCT_DISPLAY_MODE' => $this->arParentParams['PRODUCT_DISPLAY_MODE'],
    'PRODUCT_BLOCKS_ORDER' => $this->arParentParams['LIST_PRODUCT_BLOCKS_ORDER'],
    'PRODUCT_ROW_VARIANTS' => $this->arParentParams['LIST_PRODUCT_ROW_VARIANTS'],
    'ENLARGE_PRODUCT' => $this->arParentParams['LIST_ENLARGE_PRODUCT'],
    'ENLARGE_PROP' => isset($this->arParentParams['LIST_ENLARGE_PROP']) ? $this->arParentParams['LIST_ENLARGE_PROP'] : '',
    'SHOW_SLIDER' => $this->arParentParams['LIST_SHOW_SLIDER'],
    'SLIDER_INTERVAL' => isset($this->arParentParams['LIST_SLIDER_INTERVAL']) ? $this->arParentParams['LIST_SLIDER_INTERVAL'] : '',
    'SLIDER_PROGRESS' => isset($this->arParentParams['LIST_SLIDER_PROGRESS']) ? $this->arParentParams['LIST_SLIDER_PROGRESS'] : '',

    'OFFER_ADD_PICT_PROP' => $this->arParentParams['OFFER_ADD_PICT_PROP'],
    'OFFER_TREE_PROPS' => (isset($this->arParentParams['OFFER_TREE_PROPS']) ? $this->arParentParams['OFFER_TREE_PROPS'] : []),
    'PRODUCT_SUBSCRIPTION' => $this->arParentParams['PRODUCT_SUBSCRIPTION'],
    'SHOW_DISCOUNT_PERCENT' => $this->arParentParams['SHOW_DISCOUNT_PERCENT'],
    'DISCOUNT_PERCENT_POSITION' => $this->arParentParams['DISCOUNT_PERCENT_POSITION'],
    'SHOW_OLD_PRICE' => $this->arParentParams['SHOW_OLD_PRICE'],
    'SHOW_MAX_QUANTITY' => $this->arParentParams['SHOW_MAX_QUANTITY'],
    'MESS_SHOW_MAX_QUANTITY' => (isset($this->arParentParams['~MESS_SHOW_MAX_QUANTITY']) ? $this->arParentParams['~MESS_SHOW_MAX_QUANTITY'] : ''),
    'RELATIVE_QUANTITY_FACTOR' => (isset($this->arParentParams['RELATIVE_QUANTITY_FACTOR']) ? $this->arParentParams['RELATIVE_QUANTITY_FACTOR'] : ''),
    'MESS_RELATIVE_QUANTITY_MANY' => (isset($this->arParentParams['~MESS_RELATIVE_QUANTITY_MANY']) ? $this->arParentParams['~MESS_RELATIVE_QUANTITY_MANY'] : ''),
    'MESS_RELATIVE_QUANTITY_FEW' => (isset($this->arParentParams['~MESS_RELATIVE_QUANTITY_FEW']) ? $this->arParentParams['~MESS_RELATIVE_QUANTITY_FEW'] : ''),
    'MESS_BTN_BUY' => (isset($this->arParentParams['~MESS_BTN_BUY']) ? $this->arParentParams['~MESS_BTN_BUY'] : ''),
    'MESS_BTN_ADD_TO_BASKET' => (isset($this->arParentParams['~MESS_BTN_ADD_TO_BASKET']) ? $this->arParentParams['~MESS_BTN_ADD_TO_BASKET'] : ''),
    'MESS_BTN_SUBSCRIBE' => (isset($this->arParentParams['~MESS_BTN_SUBSCRIBE']) ? $this->arParentParams['~MESS_BTN_SUBSCRIBE'] : ''),
    'MESS_BTN_DETAIL' => (isset($this->arParentParams['~MESS_BTN_DETAIL']) ? $this->arParentParams['~MESS_BTN_DETAIL'] : ''),
    'MESS_NO_PRICE' => (isset($this->arParentParams['~MESS_NO_PRICE_SECTION']) ? $this->arParentParams['~MESS_NO_PRICE_SECTION'] : ''),
    'MESS_NOT_AVAILABLE' => (isset($this->arParentParams['~MESS_NOT_AVAILABLE']) ? $this->arParentParams['~MESS_NOT_AVAILABLE'] : ''),
    'MESS_BTN_COMPARE' => (isset($this->arParentParams['~MESS_BTN_COMPARE']) ? $this->arParentParams['~MESS_BTN_COMPARE'] : ''),

    'USE_ENHANCED_ECOMMERCE' => (isset($this->arParentParams['USE_ENHANCED_ECOMMERCE']) ? $this->arParentParams['USE_ENHANCED_ECOMMERCE'] : ''),
    'DATA_LAYER_NAME' => (isset($this->arParentParams['DATA_LAYER_NAME']) ? $this->arParentParams['DATA_LAYER_NAME'] : ''),
    'BRAND_PROPERTY' => (isset($this->arParentParams['BRAND_PROPERTY']) ? $this->arParentParams['BRAND_PROPERTY'] : ''),
    'SECTION_USER_FIELDS'=> ['UF_*'],

    'TEMPLATE_THEME' => (isset($this->arParentParams['TEMPLATE_THEME']) ? $this->arParentParams['TEMPLATE_THEME'] : ''),
    "ADD_SECTIONS_CHAIN" => "Y",
    'SHOW_CLOSE_POPUP' => isset($this->arParentParams['COMMON_SHOW_CLOSE_POPUP']) ? $this->arParentParams['COMMON_SHOW_CLOSE_POPUP'] : '',
    'COMPARE_PATH' => $this->arParentResult['FOLDER'].$this->arParentResult['URL_TEMPLATES']['compare'],
    'COMPARE_NAME' => $this->arParentParams['COMPARE_NAME'],
    'USE_COMPARE_LIST' => 'Y',
    'BACKGROUND_IMAGE' => (isset($this->arParentParams['SECTION_BACKGROUND_IMAGE']) ? $this->arParentParams['SECTION_BACKGROUND_IMAGE'] : ''),
    'COMPATIBLE_MODE' => (isset($this->arParentParams['COMPATIBLE_MODE']) ? $this->arParentParams['COMPATIBLE_MODE'] : ''),
    "SHOW_ALL_WO_SECTION" => $this->arParentParams['SHOW_ALL_WO_SECTION'],
    'DISABLE_INIT_JS_IN_COMPONENT' => (isset($this->arParentParams['DISABLE_INIT_JS_IN_COMPONENT']) ? $this->arParentParams['DISABLE_INIT_JS_IN_COMPONENT'] : ''),
];