<?php

namespace Sprint\Migration;

use Bitrix\Iblock\PropertyTable;
use Bitrix\Main\Loader;

class CatalogRussianProperties20201030124347 extends Version
{
    protected $description = "";

    protected $moduleVersion = "3.12.17";

    public function up()
    {

        Loader::includeModule('iblock');

        $names = [
            'Поддержка 3D',
            'Поддержка 4К',
            'Акустическое оформление',
            'Встроенный АЦП и цифровые выходы',
            'Аксессуар',
            'Аналоговые входы',
            'Аналоговые выходы',
            'Аудио/видео стриминг',
            'Bi-wiring',
            'Bluetooth',
            'Производитель',
            'Съёмный кабель',
            'Проводные/Беспроводные',
            'Цифровые входы',
            'Цифровые выходы',
            'Цвет',
            'Глубина (мм)',
            'Диагональ (дюйм)',
            'Диаметр колонки (мм)',
            'Вид аксессуара для проектора',
            'Длина кабеля (м)',
            'Длина тонарма (в дюймах)',
            'Поддержка DSD',
            'Эффективная масса (г)',
            'Встроенный фонокорректор',
            'Формат картинки',
            'Поддержка FullHD',
            'Головка в комплекте',
            'Готовые/в нарезку',
            'Высота (мм)',
            'Импеданс (Ом)',
            'Internet-радио и стриминг',
            'Количество каналов',
            'Колонки в комплекте',
            'Контрастность',
            'Максимальная нагрузка (кг)',
            'Максимальная частота дискретизации (кГц)',
            'Максимальная частота (Гц)',
            'Максимальная разрядность (бит)',
            'Минимальная частота (Гц)',
            'Выход предусилителя (многоканальный)',
            'Монтажная глубина (мм)',
            'Мощность на канал (8 Ом) Вт',
            'Мощность на канал (4 Ом) Вт',
            'Тип устройства Multiroom',
            'Настройка параметров',
            'Тип устройства питания',
            'Плеер/транспорт',
            'Поддержка карт памяти',
            'Поддержка SACD',
            'Количество полок',
            'Привод',
            'Проектор/экран/аксессуар',
            'Разъём наушников',
            'Тип разъёма (отдельный)',
            'Ресивер/Процессор',
            'Сдвиг линз',
            'Сечение проводников (кв.мм)',
            'Чувствительность (дБ)',
            'Сенсорный экран',
            'Шумоподавление',
            'Скорость вращения 78',
            'Стерео выход',
            'Тип стойки',
            'Тип экрана',
            'Тип головки',
            'Тип кабеля',
            'Тип фонокорректора (лампа или транзистор)',
            'Тип кронштейна',
            'Тип наушников',
            'Тип проектора',
            'Тип разъёма на кабеле',
            'Вид товара',
            'Тип портативного устройства',
            'Тонарм в комплекте',
            'Встроенный ЦАП',
            'Вид акустических систем',
            'Тип излучателей',
            'Тип усилителя',
            'Вес головки (г)',
            'Вес проектора',
            'Входы фонокорректора',
            'Входы HDMI',
            'Вид аксессуара',
            'Вид фонокорректора (ММ или МС)',
            'Вид Multiroom устройства',
            'Вид наушников',
            'Вид тонарма',
            'Вид усилителя',
            'Выход на наушники',
            'Выход предусилителя',
            'Выходы фонокорректора',
            'Выходы HDMI',
            'Выходы на сабвуфер',
            'Выходное напряжение (мВ)',
            'Высота стойки (мм)',
            'Воспроизведение CD',
            'Воспроизведение USB',
            'Встроенный предусилитель',
            'Встроенный усилитель для наушников',
            'Wi-Fi',
            'Ширина (мм)',
            'Балансные входы (XLR)',
            'Балансные выходы (XLR)',
            'Яркость',
        ];
        $codes = [
            '3d',
            '4k',
            'acoustic-oformlenie',
            'adcin',
            'aksessuar',
            'analogovie-vhodi',
            'analogovie-vihodi',
            'audio-video-striming',
            'bi-wiring',
            'bluetooth',
            'brend',
            'cabell',
            'cable-wirwless',
            'cifrovie-vhodi',
            'cifrovie-vihodi',
            'colour',
            'depth',
            'diagonal',
            'diametr-kolonki',
            'dla-proektora',
            'dlina',
            'dlina-tonarma',
            'dsd',
            'effektivnaja-massa',
            'fonokorrector',
            'format-kartinki',
            'fullhd',
            'golovka',
            'gotovie',
            'height',
            'impedance',
            'internet',
            'kolichestvo-kanalov',
            'kolonki-komplekt',
            'kontrastnoct',
            'max-nagruzka',
            'maximum-discretizatcia',
            'maximum-frequency',
            'maximum-razriadnost',
            'minimum-frequency',
            'mnogokanalnij-vihod',
            'montaj-glubina',
            'mozhnost-na-kanal',
            'mozhnost-na-kanal-4om',
            'multiroom',
            'nastrojka-parametrov',
            'pitanie',
            'pleer-transport',
            'poddergka-kart',
            'podderjka-sacd',
            'polki',
            'privod',
            'proektor-ekran',
            'raz',
            'razem',
            'reciver-processor',
            'sdvig-linz',
            'sechenie',
            'sensitivity',
            'sensornij',
            'shum',
            'speed',
            'stereo-vihod',
            'stoika',
            'tip-ekrana',
            'tip-golovki',
            'tip-kabelia',
            'tip-korrektora',
            'tip-kronshteina',
            'tip-naushnikov',
            'tip-proektora',
            'tip-razema',
            'tip-tovara',
            'tip-ustrojstva',
            'tonarm-komplekt',
            'tsap',
            'type-acoustic-system',
            'type-izluchateli',
            'usilitel-type',
            'ves-golovki',
            'ves-proektora',
            'vhodi-fonokorrektora',
            'vhodi-hdmi',
            'vid-aksessuara',
            'vid-korrektora',
            'vid-multiroom-usrtojstva',
            'vid-naushniki',
            'vid-tonarma',
            'vid-usilitel',
            'vihod-na-naushniki',
            'vihod-predusilitelya',
            'vihodi-fonokorrektora',
            'vihodi-hdmi',
            'vihodi-na-subwoofer',
            'vihodnoe',
            'visota',
            'vosproizvedenie-cd',
            'vosproizvedenie-usb',
            'vstroennij-predusilitel',
            'vstroennij-usilitel-naush',
            'wi-fi',
            'width',
            'xlr',
            'xlr-vihod',
            'yarkost',
        ];
        $helper = $this->getHelperManager();
        $iblockId = $helper->Iblock()->getIblockIdIfExists('catalog', 'catalog');

        $properties = PropertyTable::query()
            ->setSelect(['NAME', 'ID', 'CODE'])
            ->where('IBLOCK_ID', $iblockId)
            ->whereIn('NAME', $codes)
            ->fetchCollection();

        foreach($properties as $property) {
            $foundIdx = array_search($property->getName(), $codes);
            if($foundIdx !== false) {
                $property->setName($names[$foundIdx]);
                $property->save();
            }
        }
    }

    public function down()
    {
        //your code ...
    }
}
